name: DOCKER CI-CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          cd ./EmployeeRegister
          sudo apt install nodejs
          sudo apt install npm
          npm install -g @angular/cli
          npm install --force @angular-devkit/build-angular
          ng test --no-watch --code-coverage
          cat ./coverage/employee-register/lcov.info
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: ./EmployeeRegister
        file: ./EmployeeRegister/Dockerfile
        tags: index.docker.io/${{secrets.DOCKERHUB_USERNAME}}/employeeregisterui:${{github.sha}}
        push: true
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'employeeregisterui'
        publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE_EMPLOYEEREGISTERUI}}
        images: index.docker.io/${{secrets.DOCKERHUB_USERNAME}}/employeeregisterui:${{github.sha}}
